version: '3.8'

services:

  auth-db-postgres:
    container_name: auth-db-postgres
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

  redis:
     image: redis:latest
     container_name: redis
     ports:
       - "6379:6379"


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"


