version: '3.8'

services:

  auth-db-postgres:
    container_name: auth-db-postgres
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

#   couchbase-db:
#     container_name: db
#     image: couchbase:community-7.2.2
#     ports:
#       - "8091-8097:8091-8097"
#       - "9123:9123"
#       - "11207:11207"
#       - "11210:11210"
#       - "11280:11280"
#       - "18091-18097:18091-18097"
#     volumes:
#       - chatfy-data:/opt/couchbase/var


#   contact-db-neo4j:
#     container_name: contact-db-neo4j
#     image: neo4j:bullseye
#     ports:
#       - "7474:7474"
#       - "7687:7687"
#     volumes:
#       - chatfy-contact-db:/data


#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - chatfy-redis-data:/data



# volumes:
#     chatfy-data:
#     chatfy-auth-db:
#     chatfy-contact-db:
#     chatfy-redis-data:
